# Developer---->|                    |----> External tool (eg. gitlint)
#               |----> makefile ---->|
# CI System---->|                    |----> External tool (eg. mypy)

name: debpic

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install debpic
      run: |
        mkdir -p /tmp/debpic
        gh release download --repo "$GITHUB_REPOSITORY" --pattern '*.deb' --dir /tmp/debpic
        sudo apt-get update
        sudo apt-get install --yes /tmp/debpic/*.deb
        sudo usermod -aG docker $USER
        newgrp docker
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Black
      run: |
        make -f checks.mk black
    - name: Isort
      run: |
        make -f checks.mk isort
    - name: Mypy
      run: |
        make -f checks.mk mypy
    - name: Pytest
      run: |
        make -f checks.mk pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Package
      run: |
        make -f checks.mk package
    - name: Lintian
      run: |
        make -f checks.mk lintian
    - name: Clean
      run: |
        make -f checks.mk clean
    - uses: actions/upload-artifact@v4
      with:
        name: Debian Package
        path: ./built_packages/debpic*.deb
        if-no-files-found: error
