# Developer---->|                    |----> External tool (eg. gitlint)
#               |----> makefile ---->|
# CI System---->|                    |----> External tool (eg. mypy)

name: debpic

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install debpic
      run: |
        wget https://github.com/aidan-gallagher/debpic/releases/download/v1.0.0/debpic_1.0.0_all.deb
        sudo apt install ./debpic_1.0.0_all.deb
        sudo usermod -aG docker $USER
        newgrp docker
    - name: Black
      run: |
        make -f checks.mk black
    - name: Mypy
      run: |
        make -f checks.mk mypy
    - name: Pytest
      run: |
        make -f checks.mk pytest
    - name: Package
      run: |
        make -f checks.mk package
    - name: Lintian
      run: |
        make -f checks.mk lintian
    - name: Clean
      run: |
        make -f checks.mk clean
    - uses: actions/upload-artifact@v3
      with:
        name: Debian Package
        path: ./built_packages/debpic*.deb
        if-no-files-found: error
